#
#--------------------------------------------------------------------------
# Image setup
#--------------------------------------------------------------------------
#

ARG NODE_VERSION=23

# Use a specific Node.js version as the base image. Alpine is a lightweight Linux distribution.
FROM node:${NODE_VERSION}-alpine

# Install curl
RUN apk --no-cache add curl

# Set the working directory inside the container
WORKDIR /var/www/hiwici.github.io

# Copy package.json and lock files to install dependencies
COPY package*.json ./

# Install dependencies (use npm, yarn, or pnpm based on your project)
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port Nuxt uses (default is 3000)
EXPOSE 3000

# Command to run the Nuxt dev server.
# Crucially, set the host to 0.0.0.0 so it's accessible outside the container
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]