version: '3.8'

### Network ################################################
networks:
  workspace:
    external: true

### Service ################################################
services:
  hiwici.github.io:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: hiwici.github.io
    image: hiwici.github.io
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - .:/var/www/hiwici.github.io
      - /var/www/hiwici.github.io/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - workspace
